graph TD

%% Define colors
classDef repo_type fill:#ef8d22,stroke:#333,stroke-width:2px; %% orange
classDef submodule_type fill:#c7e8ac,stroke:#333,stroke-width:2px; %% green
classDef code_type fill:#c1e4f7,stroke:#333,stroke-width:2px; %% blue
classDef nb_type fill:#ffeca9,stroke:#333,stroke-width:2px; %% yellow
classDef inprogress stroke-dasharray: 5, 5

%% Set edges to be curved (try monotoneX for a nice alternative)
linkStyle default interpolate basis;

%%org((a2e-mmc organization))
%%org --> assessment
assessment
class assessment repo_type

assessment --> datasets(datasets)
assessment --> studies(studies)
datasets --> swift(SWiFT)
datasets --> wfip2(WFIP2)
datasets --> fino(FINO)
datasets --> nyserda(NYSERDA)
swift --> TTUtower[TTU tower<br>analysis]
swift --> TTUradar[TTU radar<br>analysis]
wfip2 --> Wasco[Wasco<br>analyses]
wfip2 --> physsite[Physics Site<br>analyses]
fino --> FINO1[FINO1<br>analysis]
nyserda --> nysbuoy[NYSERDA buoy<br>analyses]
studies --> couplingcomparison["coupling<br>comparison"]
studies --> perturbations["perturbation<br>methods"]
class datasets,studies submodule_type
class wfip2,swift,fino,nyserda,otherdata submodule_type
class otherdata inprogress
class TTUtower,TTUradar nb_type
class Wasco,physsite nb_type
class FINO1 nb_type
class nysbuoy nb_type
class couplingcomparison,perturbations nb_type

subgraph Legend
    repository --> subdirectory
    subdirectory --> notebooks[jupyter notebook]
    class repository repo_type
    class subdirectory submodule_type
    class notebooks nb_type
end
